import { Inter } from "next/font/google";
import Navbar from "@/components/CommonComps/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FrontiersDev",
  description: "Generated by two developers.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
